window:
  decorations: full
  startup_mode: Maximized
  title: Alacritty
  dynamic_title: true
font:
  normal:
    family: 'Fira Code'
  size: 16.0

colors:
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'

  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'
